📨 Show send and receive activity for all tokens
tallycash/tally-extension pull request #400
Opened 2021-11-08 17:59 UTC by henryboldi

### Send and receive activity
This PR adds send and receive activity for all tokens functionality to the activity panel on the home tab. This helps us move towards the goal of a complete home tab. 

Of note, this adds a `determineAsset` function that attempts to extract the asset data from a transactions' input data. This uses a variety of heuristics, which isn't ideal but seems to work pretty well. A part of this function deals with swaps, and that's probably the fuzziest part. I can totally chop out all the swap-related code here

<img width="360" alt="Screen Shot 248" src="https://user-images.githubusercontent.com/1918798/142935029-4616ce3e-a34f-4f83-b672-2e1d60d9a43a.png">

2021-11-22 19:36 UTC, henryboldi commented
I might sneak swap activities in here — it's pretty close 😬
<img width="380" alt="Swap" src="https://user-images.githubusercontent.com/1918798/142924100-36b73e7e-2e54-4393-bd25-1007d5519855.png">

2021-11-22 21:21 UTC, henryboldi reviewed
- Too many violations of `Tip 44: Don't Program by Coincidence`
- Could move more logic into the selector or reducer

⚠️ Updates to address my self-review coming soon. Feel free to review as well now

2021-11-22 21:21 UTC, henryboldi commented on ui/components/Wallet/WalletActivityListItem.tsx
> +                {` ${activity?.to?.slice(0, 6)}...${activity?.to?.slice(
Perhaps this formatting should be moved to the selector

2021-11-22 21:21 UTC, henryboldi commented on ui/utils/transactionInputInterpretionHelper.ts
> +      activityItem.input.includes("0x38") || activityItem.input.includes("0x18")
Tip 44: Don't Program by Coincidence 😬

2021-11-22 21:21 UTC, henryboldi commented on background/services/chain/index.ts
> +      let meta: any = false
🚩

2021-11-22 21:21 UTC, henryboldi commented on ui/components/Wallet/WalletActivityListItem.tsx
> +                  10 ** activity.asset.decimals
Likely should move this decimal conversion to inside of `determineActivityValue`, another until function, or even the selector

2021-11-23 17:27 UTC, Shadowfiend requested changes
Few blockers here, left some notes!

2021-11-23 17:27 UTC, Shadowfiend commented on background/services/chain/index.ts
> +        const tx = txFromEthersTx(result, asset, getEthereumNetwork())
Transaction asset is meant to be the base asset of the underlying network (this became clearer [after the type refactor](https://github.com/tallycash/tally-extension/blob/main/background/networks.ts#L95)), not any asset involved in the transaction! We're going to need to surface information about assets involved *in* the transaction differently.

That said, I don't know if that kind of enrichment belongs in the database vs in redux. Feels like we could do it in `adaptForUI`, where the `data` field gets adapted to contain the transaction payload + additional derived information.

2021-11-23 17:27 UTC, Shadowfiend commented on ui/utils/transactionInputInterpretionHelper.ts
> +      activityItem.input.includes("0x38") || activityItem.input.includes("0x18")
Hahaha yeah. So here's how we will actually know if this is a swap:

- The `to` address will be the address of the swap contract. This will be a constant when we release.
- The function data will be decodable using the swap ABI. Once that's included for the swap work, we can use the Ethers [parsing functions](https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--parsing) to parse transaction data into function call data. The call will be to `swapByQuote`, and may require some additional translation from 0x terms to ours.

I think if we want to get into this in the current work, we should be thinking about how we scalably add different interpreters, rather than specifically interpreting some of the bits that aren't fully fleshed out yet. But it also feels out of scope for now, and I do lean towards dropping this entirely until we've got more of the swap stuff finished, then revisiting.

2021-11-23 17:27 UTC, Shadowfiend commented on ui/utils/transactionInputInterpretionHelper.ts
> +      value = BigInt(parseInt(activityItem.input.slice(10).slice(0, 64), 16))
In general you should never use `parse*` with `BigInt`, because it risks losing precision if the string represents a number greater than `Number.MAX_SAFE_INTEGER`. Converting to `BigInt` after the fact just wraps the lost precision into a format that implies we didn't lose the precision.

To avoid the `parseInt` hop, you can pass a string directly to `BigInt` to parse it, and prefix with `0x` to ensure `BigInt` parses the string as a hexadecimal number.

2021-11-23 17:27 UTC, Shadowfiend commented on background/redux-slices/utils.ts
> +  asset: {
Above, should `isSent?` become `isSent` now that we're populating it consistently?

2021-11-23 17:32 UTC, henryboldi commented on background/redux-slices/utils.ts
> +  asset: {
Ah, totally! Thank you

2021-11-24 03:49 UTC, Shadowfiend requested changes
Love the introduction of `activity-utils` 🙌 

Still have some concerns about structure + implementation.

2021-11-24 03:49 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +  tokenDecimalValue: number
My concern with this structure is that it walks away from the existing way of capturing an asset + amount (`AssetAmount`), as well as the existing way of including decimal values alongside that information (`CompleteAssetAmount` from the accounts slice), which means any component that wants to render `ActivityItem`'s version of this information will have to be written to *only* work with `ActivityItem`'s version.

A good option here IMO is to use a name like `activityAssetAmount: CompleteAssetAmount`. This makes it clear that it's specific to the activity, and carries the `CompleteAssetAmount` information. Once #469 lands there'll be one more PR that adds the `enrich*` helpers that will make it trivial to turn an `AssetAmount` into a `CompleteAssetAmount`.

2021-11-24 03:49 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +  }
A transaction can transfer both ETH and a token—here we explicitly choose the token to display, but is that correct, or should we be treating such a transaction as a generic contract interaction instead of presenting partial information?

2021-11-24 03:49 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +  const isSwap = input?.includes("0x38") || input?.includes("0x18")
Just realized I didn't cover how this plays out in my original note, so I want to be clear that this implementation risks misidentifying non-swap transactions as swap transactions, since it's just pattern-matching against the first byte of a function selector, which has no uniqueness guarantees and, as the result of a hash function, doesn't really have any relevance guarantees either. In that scenario, the code below will pull the first swap asset address as, at worst, `0x` followed by the 70th-110th characters in the input (since indexOf returns -1 if the search string isn't found, and substring returns the whole string for negative start indices), which could be anything. Even though that will *most likely* not match a real token address, and Alchemy will *most likely* return no metadata in that scenario, you're absolutely right that a positive outcome like that is purely programming by coincidence. We should not use it.

This does bring up a design question though: is the expectation that this information will purely work for swaps using Tally swap, or that it will also appear for other swaps? If the latter, we'll need to do a lot of lifting to correctly handle the various swap possibilities–again pointing to focusing on setting up the framework for extra interpretation of transaction data rather than doing that interpretation right now.

2021-11-24 03:49 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +export function determineActivityDecimalValue(activityItem: ActivityItem) {
All these linter warnings are here for a reason :) With the exception of `adaptForUI`, we should try to fill in return types for the exported functions here.

There are some other ones above as well.

2021-11-24 03:58 UTC, henryboldi commented on background/redux-slices/utils/activity-utils.ts
> +  const isSwap = input?.includes("0x38") || input?.includes("0x18")
Is it catastrophic to risk misidentifying non-swap transactions as swap transactions? What is a rigorous way to identify a swap transaction? Couldn't this line be replaced with something more robust later on?

2021-11-24 04:17 UTC, henryboldi commented on background/redux-slices/utils/activity-utils.ts
> +  tokenDecimalValue: number
Sounds good!

2021-11-24 04:19 UTC, henryboldi commented on background/redux-slices/utils/activity-utils.ts
> +  }
How would you go about determining when a transfer is of both ETH and a token?

2021-11-24 21:16 UTC, mhluongo commented on background/redux-slices/utils/activity-utils.ts
> +  const isSwap = input?.includes("0x38") || input?.includes("0x18")
Big discussion I'm helicoptering into here, but tx introspection has been on my mind!

> Is it catastrophic to risk misidentifying non-swap transactions as swap transactions?

Maybe not catastrophic, but not great. This is people's money, and seeing the wrong thing (versus having a more generic "contract interfaction" category) can be pretty unsettling. Imagine you thought you just staked $1M in a token and your wallet tells you you swapped that for $0, for example.

> What is a rigorous way to identify a swap transaction?

In the general case, it's impossible to rigorously categorize whether an EVM transaction "is a swap" :) In our particular product though, I think what we want to do is break this idea into a few sub-problems

* Which transactions are swaps using the in-wallet swap? **For these, we should use local wallet data**
* Which transactions are swaps using a couple common protocols? **For these, you a function selector database + a contract address allowist**. This approach will catch swaps on Uniswap, Sushi, Curve, Saddle, etc.
* Which transactions are swaps using services we don't know? **This is where things become really interesting** from a product perspective, and impossible using pure engineering.

> Couldn't this line be replaced with something more robust later on?

Yes! But we want to keep `main` releasable, so this would need to be feature-flagged or made to work correctly for one of the above categories, I think? I'm sure there's some false positive % we're okay with, but I'm not sure what it is yet.

2021-11-24 22:39 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +  }
Any transaction with a nonzero `value` transmits ETH, irrespective of what else it does, basically.

2021-11-24 22:51 UTC, mhluongo commented on background/redux-slices/utils/activity-utils.ts
> +  }
I'd lean toward generic if it does both. When we include asset transfers we can make this much fancier

2021-11-29 16:38 UTC, henryboldi commented on background/redux-slices/utils/activity-utils.ts
> +  }
What would a generic asset look like in this case? @mhluongo

2021-11-29 20:19 UTC, henryboldi commented on background/redux-slices/utils/activity-utils.ts
> +  tokenDecimalValue: number
@Shadowfiend, which function(s) did you have in mind here from #469? I don't believe it includes something for `localizedDecimalAmount`. Anyway, for now, I pulled in a type for the assets to suggest the intent of consistency
```
tokenDecimalValue: AssetDecimalAmount["decimalAmount"]
```
<br/>

Alternatively, I could use `CompleteAssetAmount` with some missing values? But this screen doesn't display main currency values, so potentially `CompleteAssetAmount` isn't need

2021-11-29 20:28 UTC, henryboldi commented
I might have broke something here on the latest version 😬. Fix incoming

2021-11-29 21:00 UTC, mhluongo commented on background/redux-slices/utils/activity-utils.ts
> +  }
Oh, I meant a generic contract interaction, not a generic asset. You can imagine a tx type that's called "Contract interaction" with an icon that's a pencil or something, which has a link to Etherscan. Down the road, we break this into individual asset transfers ala Etherscan

Recent example from my own adventures. As you can see, this involved many many assets.. and while this one didn't have a base ETH value, if it were a pool with WETH in it it might have.

![Screenshot from 2021-11-29 15-58-49](https://user-images.githubusercontent.com/427505/143942181-645b7a9c-2f50-496a-9d10-4b12e0156e71.png)

2021-11-29 21:03 UTC, mhluongo commented on background/redux-slices/utils/activity-utils.ts
> +  }
Unless we originate the transaction, we don't quite know what's useful to display. Eg in Etherscan's attempt, I'd argue it has a bunch of stuff most users don't care about in a wallet. That LP tokens were minted from `0x0` is irrelevant to me as the depositor... what's relevant is that I put in a bunch of different tokens and amounts, and got out a single LP token

2021-11-29 21:05 UTC, henryboldi commented on background/redux-slices/utils/activity-utils.ts
> +  }
Given the current design for a generic contract interaction,
<img width="432" alt="contract" src="https://user-images.githubusercontent.com/1918798/143942754-7196e94a-38e5-4c20-9e5b-a42fca5f75c1.png">

Would we drop the asset line, or include the ETH and ETH value?

2021-11-29 21:08 UTC, mhluongo commented on background/redux-slices/utils/activity-utils.ts
> +  }
Good question. We should def change "from" to "to" there... and I guess we can include the asset line with ETH initially, but we should switch to having a name for the function call rather than an asset sooner rather than later.

2021-11-29 21:27 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +  tokenDecimalValue: number
See #490, but not going to block this PR on this. We can follow up with it.

2021-11-29 21:28 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +  const isSwap = input?.includes("0x38") || input?.includes("0x18")
Matt basically said everything I was going to lol, sorry for not getting back sooner 🙆

2021-11-29 21:55 UTC, Shadowfiend approved these changes
Couple of remaining notes on how to structure this overall, but I think we're at “good enough to ship the current thing and iterate”.

2021-11-29 21:55 UTC, Shadowfiend commented on background/main.ts
> +          token: await determineToken(transaction),
Not blocking, but I think we should do this in an async thunk in the activities slice. Main should be almost exclusively wiring between services and slices, and stuff like data enrichment should really stay in the slices.

Think “where would I do this if there was no main”, basically.

2021-11-29 21:55 UTC, Shadowfiend commented on background/redux-slices/utils/activity-utils.ts
> +        meta = await getTokenMetadata(pollingProviders.ethereum, result.to)
Not blocking, but it should feel like an antipattern to directly interact with any external service from the slices if we are also interacting with that service in the services.

In this particular case, we should lean on our assets slice to help us find the token information in our own data format—remember that the assets slice sees every asset the indexing service sees, and every asset in the assets slice that is a `SmartContractFungibleAsset` knows its contract address, so there's no need to go to a server to pull that information every time we see a transaction.

2021-11-29 22:02 UTC, merged