📛 The Names of Things: Look up ENS names and avatars for new wallets
tallycash/tally-extension pull request #415
Opened 2021-11-11 23:37 UTC by mhluongo

An implementation of reverse ENS resolution, enabling ENS nicknames and avatars in the menu.

Includes

- [x] A basic name service (#225)
- [x] Reverse name and avatar resolution when 

Doesn't include

- A way to add a new read-only wallet by ENS name or to send funds to an ENS name (#411)
- Any sort of "address book" functionality

![Screenshot from 2021-11-11 18-36-57](https://user-images.githubusercontent.com/427505/141383991-08c2add7-3217-40a5-996d-b1989b3c6abb.png)

![Screenshot from 2021-11-11 18-17-45](https://user-images.githubusercontent.com/427505/141383998-03c04435-d617-466b-ab3f-dd755b2b02f2.png)

Closes #12
Closes #414

2021-11-17 22:51 UTC, henryboldi requested changes
Looks good! Two questions,

- Why is the new service called just `name`?
- Should this service be added to the architecture section of the readme?

2021-11-18 00:19 UTC, mhluongo commented
> Why is the new service called just `name`?

The thought here is that DNS is Domain Name Service, ENS is Ethereum Name Service, UNS is Unstoppable Name Service, etc etc, so I thought `NameService` was appropriate. We could also do something like `NameResolutionService` or `DomainAndAddressResolutionService`... which are perhaps easier to understand? Unfortunately none of these names captures metadata like avatars and other text records :shrug: 

ENS launched what it calls a ["metadata service"](https://metadata.ens.domains/), though that also seems limiting and has overlap with `IndexingService`.

> Should this service be added to the architecture section of the readme?

I'd actually like to replace the architecture diagram with something a bit denser than ASCII art... but felt like it was outside the scope of this work lol. @Shadowfiend if you have a link to regenerate that diagram I can make a point to keep it updated

2021-11-18 06:05 UTC, henryboldi approved these changes

2021-11-18 06:05 UTC, merged

2021-11-18 12:53 UTC, Shadowfiend commented
I may well not have a great way to regenerate, will poke around and see. More likely we want to think about a different way to maintain it, or we want to keep it higher level rather than trying to describe all service interrelationships in diagram form in a set of primarily-text docs.