Add contract utility functions and distributor abi
tallycash/tally-extension pull request #425
Opened 2021-11-16 17:15 UTC by wojciech-turek

This PR introduces basic contract utility functions like `getAlchemyProvider` and `getContract`, as well as current distributor abi for future interactions.

2021-11-17 19:20 UTC, itsrachelfish commented on background/redux-slices/contract-abis/merkle-distributor.ts
> +]
How was this generated? :thinking:

2021-11-17 19:25 UTC, wojciech-turek commented on background/redux-slices/contract-abis/merkle-distributor.ts
> +]
The abi is generated after compiling a smart contract with a tool like `hardhat`.

2021-11-17 20:57 UTC, Shadowfiend commented on background/redux-slices/utils/contract-utils.ts
> +export function getAlchemyProvider(): AlchemyProvider {
Nope, this is temporary.

I would rename this `getProvider` and have it use `Provider` or `JsonRpcProvider` as the return type (even if it internally instantiates an `AlchemyProvider`).

2021-11-17 20:57 UTC, Shadowfiend commented on background/redux-slices/contract-abis/merkle-distributor.ts
> +]
@wojciech-turek I think maybe the question here is more precisely “where did you get this from and how did you generate it”, rather than “how would one go about generating this kind of thing in general” :)

2021-11-18 08:35 UTC, wojciech-turek commented on background/redux-slices/utils/contract-utils.ts
> +export function getAlchemyProvider(): AlchemyProvider {
"This looks like a job for me" - Eminem - Micheal Scott

2021-11-18 08:49 UTC, wojciech-turek commented on background/redux-slices/contract-abis/merkle-distributor.ts
> +]
Whopps sorry misunderstood, in order to create the abis you need to go to our contracts repo [here](https://github.com/tallycash/tally-contracts) and setup it locally. After running `npm install` you can run `npx hardhat compile` that will generate `artifacts` directory in which you can find compiled `contracts`. The result of a compilation is a .json file which contains amoung others two crucial fields `abi` and `bytecode`.

2021-11-18 12:55 UTC, Shadowfiend commented on background/redux-slices/contract-abis/merkle-distributor.ts
> +]
One small note: you should be using yarn instead of npm or npx in our repos. Not a huge deal for this, but for consistency with repo setup, lockfiles, etc, that's the way to go.

2021-11-18 12:59 UTC, Shadowfiend requested changes
Couple of additional notes here sorry, didn't get a chance to go deep yesterday.

2021-11-18 12:59 UTC, Shadowfiend commented on background/redux-slices/utils/contract-utils.ts
> +  abi: any[]
Can this be `ContractInterface` instead of `any[]`?

2021-11-18 12:59 UTC, Shadowfiend commented on background/redux-slices/utils/contract-utils.ts
> +  return provider
Feels like we should only instantiate one provider and then return it, no? I.e. have a global `let` that starts `undefined` but gets populated the first time `getProvider` gets called?

2021-11-18 13:16 UTC, wojciech-turek commented on background/redux-slices/utils/contract-utils.ts
> +  return provider
That is an interesting question 🤔 , what about if the user changes network. We would need to add a detection mechanism. to re-do the provider. I have tried looking for any information whether a standalone provider caches anything but to no success. By global `let` do you mean we should store provider in redux?

2021-11-18 13:18 UTC, wojciech-turek commented on background/redux-slices/utils/contract-utils.ts
> +  abi: any[]
Absolutely, very good comment.

2021-11-18 20:26 UTC, Shadowfiend commented on background/redux-slices/utils/contract-utils.ts
> +  return provider
Nah, directly in this file.

I think it's fine for now, since we don't know the final shape that the provider will take anyway.

2021-11-18 20:30 UTC, Shadowfiend commented on background/redux-slices/utils/contract-utils.ts
> +  abi: ContractInterface
Yikes, sorry—I meant the ethers type (`import { ContractInterface } from "ethers"`).

2021-11-19 08:17 UTC, wojciech-turek commented on background/redux-slices/utils/contract-utils.ts
> +  abi: ContractInterface
Changed :)

2021-11-19 15:54 UTC, Shadowfiend approved these changes
Lgtm, letting @itsrachelfish have the last look + merge privileges :grin:

2021-11-19 20:55 UTC, itsrachelfish approved these changes

2021-11-19 20:55 UTC, itsrachelfish commented on background/redux-slices/contract-abis/merkle-distributor.ts
> +]
Thanks @wojciech-turek, I was able to replicate this output by running `yarn install` and `yarn hardhat compiled` :grinning: :+1:

2021-11-19 20:58 UTC, merged